# Generated by Django 4.2.1 on 2023-05-27 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id_eafit', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Midterm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numTerm', models.PositiveSmallIntegerField()),
                ('fechaIncio', models.DateTimeField()),
                ('fechaFin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id_eafit', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='supMidterm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIncio', models.DateTimeField()),
                ('fechaFin', models.DateTimeField()),
                ('parcial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webApp.midterm')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id_eafit', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('passed_workshop', models.BooleanField()),
                ('went_mentorship', models.BooleanField()),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webApp.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='enabled_sup',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webApp.supmidterm'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.teacher'),
        ),
    ]
